# Generated by Django 4.0.4 on 2022-05-22 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0008_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True, verbose_name='Опис одим словом')),
                ('day', models.CharField(help_text='max 10 символів', max_length=10, verbose_name='день')),
                ('month', models.CharField(help_text='Вкажіть Словом', max_length=30, verbose_name='місяць')),
                ('description', models.TextField(verbose_name='Опис заходу')),
                ('text', models.TextField(blank=True, help_text="Необов'язкове поле", verbose_name='Повний опис заходу')),
                ('image', models.ImageField(upload_to='blog_images', verbose_name='зображення блогу')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.team')),
            ],
        ),
    ]
