# Generated by Django 4.0.4 on 2022-05-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Назва категорії')),
                ('number', models.IntegerField(blank=True, verbose_name='кількість записів даної категорії')),
            ],
        ),
    ]
