# Generated by Django 4.0.4 on 2022-05-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='day',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='month',
        ),
    ]
