# Generated by Django 4.0.4 on 2022-05-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='day',
            field=models.CharField(max_length=10, verbose_name='день'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(verbose_name='Опис заходу'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='month',
            field=models.CharField(max_length=30, verbose_name='місяць'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='Опис одим словом'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='зображення профілю'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, verbose_name="ім'я та прізвище"),
        ),
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(max_length=50, verbose_name='посада або роль'),
        ),
    ]
