# Generated by Django 4.0.4 on 2022-05-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_blog_day_alter_blog_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='day',
            field=models.CharField(help_text='max 10 символів', max_length=10, verbose_name='день'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='month',
            field=models.CharField(help_text='Вкажіть Словом', max_length=30, verbose_name='місяць'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
