# Generated by Django 4.0.4 on 2022-05-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_blog_day_alter_blog_month_alter_team_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
