# Generated by Django 4.0.4 on 2022-05-23 08:37

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='home/images')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок про себе')),
                ('text', models.TextField(verbose_name='Опис про себе')),
                ('address', models.CharField(max_length=30, verbose_name='Адреса')),
                ('email', models.EmailField(max_length=254, verbose_name='Імейл власника сайту')),
                ('phone', models.CharField(max_length=13, verbose_name='Номер телефону власника')),
            ],
        ),
    ]
